---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: raspbian
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible
verifier:
  name: ansible
