---
dependency:
  name: galaxy
driver:
  name: docker
#lint: |
#  set -e
#  yamllint .
#  ansible-lint -x 503
#  flake8
platforms:
  - name: raspbian
    image: balenalib/raspberrypi4-64-debian
provisioner:
  name: ansible
scenario:
  name: default
  converge_sequence:
    - prepare
    - converge
verifier:
  name: testinfra
