---
- name: prepare
  hosts: all
  become: true
  tasks:
    - name: add user group
      user:
        name: 'pi'
        state: present
    - name: add user
      user:
        name: 'pi'
        group: 'pi'
