name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare environment
        run: |
          sudo apt update
          sudo apt -y upgrade
          curl -fsSL https://get.docker.com | sudo bash
          sudo apt install python3 python3-pip virtualenv
  
      - name: Run tests
        run: |
          source source.me
          ansible --version
          molecule --version
          docker --version
          pip3 show molecule-docker
          export SYNC_SERVER_IMAGE="balenalib/amd64-debian-python"
          molecule test
          
      - name: galaxy
        uses: robertdebock/galaxy-action@1.1.0
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
