name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare environment
        run: |
          curl -fsSL https://get.docker.com | sudo bash
          sudo apt install python3 pip3 virtualenv
        
      # Runs a single command using the runners shell
      - name: Prepare environment
        run: source setup.sh

      # Runs a set of commands using the runners shell
      - name: Run Molecule Test
        run: molecule test -s delegate
