name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare environment
        run: |
          apt update
          apt -y upgrade
          curl -fsSL https://get.docker.com | sudo bash
          sudo apt install python3 python3-pip virtualenv
  
      - name: Run tests
        run: |
          source setup.sh
          ansible --version
          molecule --version
          docker --version
          pip3 show molecule-docker
          molecule --debug -vvv test -s delegate
