name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: umacos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare environment
        run: |
          curl -fsSL https://get.docker.com | sudo bash
          sudo apt install python3 python3-pip virtualenv
        
      # Runs a single command using the runners shell
      - name: Prepare environment
        run: |
          source setup.sh
          molecule --debug -vvv test -s delegate
