name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: debug info
        run: |
          ansible --info
          molecule --info
          docker --info
          pip3 show molecule-docker

      - name: Prepare environment
        run: |
          curl -fsSL https://get.docker.com | sudo bash
          sudo apt install python3 python3-pip virtualenv
  
      - name: Run tests
        run: |
          source setup.sh
          molecule --debug -vvv test -s delegate
